language: objective-c
osx_image:
  - xcode9.2
  - xcode9.3beta
xcode_project: ParallelFlock.xcodeproj # path to your xcodeproj folder
xcode_scheme:
  - iOS Tests
  - macOS Tests
  - tvOS Tests
before_install:
- brew update && brew bundle
