matrix:
  include:
    - {osx_image: xcode9.2,     env: 'SCHEME="macOS Framework" PLATFORM="platform=OS X,arch=x86_64"', os: osx, language: objective-c}
    - {osx_image: xcode9.2,     env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPhone 7 Plus,OS=11.2"', os: osx, language: objective-c}
    - {osx_image: xcode9.2,     env: 'SCHEME="tvOS Framework" PLATFORM="platform=tvOS Simulator,name=Apple TV,OS=11.2"', os: osx, language: objective-c}
    
    - {osx_image: xcode9.3beta,     env: 'SCHEME="macOS Framework" PLATFORM="platform=OS X,arch=x86_64"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPhone 7 Plus,OS=11.2"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="tvOS Framework" PLATFORM="platform=tvOS Simulator,name=Apple TV,OS=11.2"', os: osx, language: objective-c}
before_install:
- brew update && brew bundle
script:
- xcodebuild -project ParallelFlock.xcodeproj -scheme "$SCHEME" -destination "$PLATFORM" -enableCodeCoverage YES test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
