language: objective-c
branches:
  only:
    - master
    - release/1.0.0
matrix:
  include:
    - {osx_image: xcode9.2,         env: 'SCHEME="macOS Framework" PLATFORM="platform=OS X,arch=x86_64" SUFFIX="macOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="macOS Framework" PLATFORM="platform=OS X,arch=x86_64" SUFFIX="macOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPhone 4s,OS=8.1" SUFFIX="iOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPhone 6 Plus,OS=8.4" SUFFIX="iOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPhone 6 Plus,OS=9.0" SUFFIX="iOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPhone 4s,OS=9.3" SUFFIX="iOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPhone 5,OS=10.0" SUFFIX="iOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPhone 5,OS=10.3" SUFFIX="iOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPhone 5s,OS=11.0" SUFFIX="iOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPhone X,OS=11.1" SUFFIX="iOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.2,         env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPad Pro (10.5-inch),OS=11.2" SUFFIX="iOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPad (5th generation),OS=11.2" SUFFIX="iOS"', os: osx, language: objective-c}    
    - {osx_image: xcode9.3beta,     env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPhone X,OS=11.3" SUFFIX="iOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPhone 7,OS=11.3" SUFFIX="iOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="tvOS Framework" PLATFORM="platform=tvOS Simulator,name=Apple TV 1080p,OS=9.2" SUFFIX="tvOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="tvOS Framework" PLATFORM="platform=tvOS Simulator,name=Apple TV 1080p,OS=10.2" SUFFIX="tvOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="tvOS Framework" PLATFORM="platform=tvOS Simulator,name=Apple TV 1080p,OS=11.0" SUFFIX="tvOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="tvOS Framework" PLATFORM="platform=tvOS Simulator,name=Apple TV 4K,OS=11.2" SUFFIX="tvOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="tvOS Framework" PLATFORM="platform=tvOS Simulator,name=Apple TV 4K,OS=11.3" SUFFIX="tvOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.2,         env: 'SCHEME="tvOS Framework" PLATFORM="platform=tvOS Simulator,name=Apple TV 4K (at 1080p),OS=11.2" SUFFIX="tvOS"', os: osx, language: objective-c}
before_install:
- brew update && brew bundle
- bundle install
script:
- xcodebuild -project ParallelFlock.xcodeproj -scheme "$SCHEME" -destination "$PLATFORM" -enableCodeCoverage YES test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -skip-testing:ParallelFlockTests_$SUFFIX/ParallelFlockPerformanceTests | xcpretty -f `xcpretty-travis-formatter`

