language: objective-c
matrix:
  include:
    - {osx_image: xcode9.2,     env: 'SCHEME="macOS Framework" PLATFORM="platform=OS X,arch=x86_64"', os: osx, language: objective-c}
   # - {osx_image: xcode8.3,     env: 'SWFT=3.1  PLAT=iOS      DST="OS=10.3.1,name=iPhone SE"',       os: osx, language: objective-c}
before_install:
- brew update && brew bundle
script:
- xcodebuild -project ParallelFlock.xcodeproj -scheme $SCHEME -destination '$PLATFORM' -enableCodeCoverage YES test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
#- xcodebuild -project ParallelFlock.xcodeproj -scheme "iOS Framework" -destination "platform=iOS Simulator,name=iPhone 7 Plus,OS=11.2" -enableCodeCoverage YES test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
#- xcodebuild -project ParallelFlock.xcodeproj -scheme "tvOS Framework" -destination "platform=tvOS Simulator,name=Apple TV,OS=11.2" -enableCodeCoverage YES test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
