language: objective-c
matrix:
  include:
    - {osx_image: xcode9.2,     env: 'SCHEME="macOS Framework" PLAT='platform=OS X,arch=x86_64'}
before_install:
- brew update && brew bundle
script:
- xcodebuild -project ParallelFlock.xcodeproj -scheme $SCHEME -destination '$PLATFORM' -enableCodeCoverage YES test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
#- xcodebuild -project ParallelFlock.xcodeproj -scheme "iOS Framework" -destination "platform=iOS Simulator,name=iPhone 7 Plus,OS=11.2" -enableCodeCoverage YES test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
#- xcodebuild -project ParallelFlock.xcodeproj -scheme "tvOS Framework" -destination "platform=tvOS Simulator,name=Apple TV,OS=11.2" -enableCodeCoverage YES test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
