language: objective-c
branches:
  only:
    - master
    - feature/codecov
    - release/1.0.0
matrix:
  include:
    - {osx_image: xcode9.2,         env: 'SCHEME="macOS Framework" PLATFORM="platform=OS X,arch=x86_64" SUFFIX="macOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="macOS Framework" PLATFORM="platform=OS X,arch=x86_64" SUFFIX="macOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPhone 4s,OS=8.1" SUFFIX="iOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPhone 4s,OS=9.3" SUFFIX="iOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPhone 5,OS=10.3.1" SUFFIX="iOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.2,         env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPad Pro (10.5-inch),OS=11.2" SUFFIX="iOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="iOS Framework" PLATFORM="platform=iOS Simulator,name=iPhone X,OS=11.3" SUFFIX="iOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="tvOS Framework" PLATFORM="platform=tvOS Simulator,name=Apple TV 1080p,OS=9.2" SUFFIX="tvOS"', os: osx, language: objective-c}
    - {osx_image: xcode9.3beta,     env: 'SCHEME="tvOS Framework" PLATFORM="platform=tvOS Simulator,name=Apple TV 4K,OS=11.3" SUFFIX="tvOS"', os: osx, language: objective-c}
before_install:
- brew bundle
- bundle install
- defaults write com.apple.dt.Xcode BuildSystemScheduleInherentlyParallelCommandsExclusively -bool NO
script:
- xcodebuild -project ParallelFlock.xcodeproj -scheme "$SCHEME" -destination "$PLATFORM" -enableCodeCoverage YES ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -skip-testing:ParallelFlockTests_$SUFFIX/ParallelFlockPerformanceTests 
after_success:
- bash <(curl -s https://codecov.io/bash)  -X xcodeplist -c -F "$PLATFORM"

