language: objective-c
matrix:
  include:
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode9.3beta
xcode_project: ParallelFlock.xcodeproj # path to your xcodeproj folder
xcode_scheme:
  - "iOS Framework"
  - "macOS Framework"
  - "tvOS Framework"
before_install:
- brew update && brew bundle
